### ISSUE TITLE
Error in agent.load_data when using FallbackPolicy

### ISSUE THREAD

**Issue by miguelvr** [RasaHQ/rasa_core#621]
**Rasa Core version**: 0.9.4
**Python version**:  3.6.4
**Operating system**: Ubuntu 16.04 LTS

**Issue**:
When using the `FallbackPolicy` to train the dialogue model, I get an error on `agent.load_data(training_data_file)`

This is due to the fact of `FallbackPolicy` having `MAX_HISTORY_DEFAULT = None` and in `agent.load_data` the following code is executed:

https://github.com/RasaHQ/rasa_core/blob/c8b15aca63f2ea76f1852823742a10e0e7eda0c5/rasa_core/agent.py#L195-L204

eventually we're trying to compare a `None` with an integer.

I can make a PR but I'm not sure what the correct behavior here is. Is `MAX_HISTORY_DEFAULT = None` correct? Or should we just check for `None`s when computing `max_max_history`?

Best regards,
Miguel

**Comment by miguelvr** [comment]
I guess this was solved 6 days ago in master, just not in the latest stable version.

**Comment by Ghostvv** [comment]
@miguelvr you're right, this problem is solved on `master` and `0.9.x` branches

**Comment by tmbo** [comment]
but there wasn't a release with this fix yet, @Ghostvv right?

**Comment by Ghostvv** [comment]
@tmbo I do not think so. I think the released version is still broken

**Comment by shona20** [comment]
training_data = agent.load_data('my_stories.md')
agent.train(
       training_data,
       validation_split=0.0,

NameError: name 'agent' is not defined


please help with the error

**Comment by tmbo** [comment]
this is a completely different issue, if you need further help, please open a separate issue.
